#!/bin/bash

if [ -z "$VIRTUAL_ENV" ]; then
    echo "You should activate the virtualenv before running this command."
    echo "$ source venv/bin/activate"
    exit 1
fi

result=0

for REPO in ranker srcomp srcomp-http
do
    pushd $REPO
    python setup.py test
    result=$((result | $?))
    popd
done

exit $result
