#!/bin/bash

if [ -z "$VIRTUAL_ENV" ]; then
    echo "You should activate the virtualenv before running this command."
    echo "$ source venv/bin/activate"
    exit 1
fi

result=0

for REPO in ranker srcomp srcomp-cli srcomp-http srcomp-scorer
do
    pushd $REPO
    if [ -e run-tests ]
    then
        # Convenience wrapper present in some repos
        ./run-tests
    else
        # Most common (but not universal) underlying entrypoint
        script/testing/test
    fi
    result=$((result | $?))
    popd
done

exit $result
