#!/bin/bash

if [ -z "$VIRTUAL_ENV" ]; then
    echo "You should activate the virtualenv before running this command."
    echo "$ source venv/bin/activate"
    exit 1
fi

for REPO in ranker srcomp srcomp-http
do
    cd $PWD/$REPO
    python setup.py test
done
